### PR TITLE
Avoid throwing of runtime exception

### PR DESCRIPTION
**Pull request by anshunjain**
get stacktrace by reflecting on the current thread

### CODE REVIEW

**Comment by greenlaw110** [comment]
Nice! But there requires a fix to make it work. See the screenshot below:

image

Look at the mark `#3`, it gives me the `act.Act` as class name, however what I really need is at mark `#4`: `demo.helloworld.HelloWorldApp`, in order to find out the default scan package `demo.helloworld`. So you must change the index see mark `#2` to get the correct class info from the stack trace.

Please submit a fix and then I will merge your PR.

**Comment by greenlaw110** [comment]
Well actually I checked the `Thread.getStackTrace()` code and found it is using the `Exception.getStackTrace()` method:

image

That means probably calling to `Thread.currentThread().getStackTrace()` might **not** be a better way because

1. it waste CPU on `Thread.currentThread()` call
2. it fills in one additional call stack into the returning stack trace element array

What do you reckon?

**Comment by anshunjain** [comment]
You are very right. I was being naive, in not looking at the inside of Thread.getCurrentThread(). Almost disappointing a Throwable needs to be created. I am digging deeper now to see if there is something more optimal to get the calling function we seek here. (I have used this same call in a runtime logging interface for some of my code, where this is invoked for every REST call).

**Comment by anshunjain** [comment]
http://stackoverflow.com/questions/26116181/access-stacktraces-with-good-performance
gives some alternative, but tricky ways to do this using SharedSecrets. Will try it, but may not be worth it for the above use case. apparently Java 9 will come with StackWalker interface. looking forward to that. http://download.java.net/java/jdk9/docs/api/java/lang/StackWalker.html

**Comment by greenlaw110** [comment]
I am not too worry about improve the `getStrackTrace()` performance in this particular pieace of Act code cause it is called only one time when you bootup the app without supplying the package name. literally nothing to worry about.

However I need to generate the stacktrace on every REST call I will be very concerned...

**Pull request closed without merging**
